[project]
name = "WorkoutBoard"
version = "1.0.0"
description = "Home Gym Workout Guide"
dependencies = [
    "flask",
    "waitress",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"